title: <p align="center">Komal Mahawar</p>
logo: /assets/img/IMG-20200707-WA0005.jpg
description:
  <p align="center">
  <a href="https://github.com/KomalMahawar">GitHub</a>
  </p>

theme: jekyll-theme-minimal
