title: <p align="center">Komal Mahawar</p>
logo: /assets/img/IMG-20200707-WA0005.jpg
description: 
  <html> <p align="center">
    <a href="https://www.linkedin.com/in/komalmahawar/">LinkedIn</a> |
    <a href="https://github.com/KomalMahawar/">GitHub</a>Minimal is a theme for GitHub Pages.
  </p> </html>

theme: jekyll-theme-minimal
